config/routes.rb
Rails.application.routes.draw do
 
  resources :questions do 
  	resources :answers do 
  		member do
  			post :vote
  		end
  	end
end

  root :to => 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description, presence: true

  scope :by_votes, -> { order ("votes DESC") }
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers

	def top_answer 
		top_answer = self.answers.by_votes.first
		if top_answer.present?
			top_answer.description
		else
			"Be the first to answer this question!"
		end
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

def create
	@question = Question.find(params[:question_id])
	@answer = @question.answers.new(params.require(:answer).permit(:description))
	if @answer.save
		redirect_to question_url(@question)
	else
		redirect_to question_url(@question)
	end
end

def vote
	@question = Question.find(params[:question_id])
	@answer = Answer.find(params[:id])
	@answer.votes += 1
	@answer.save
	redirect_to question_url(@question)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.all
	end

	def new
		@question = Question.new
	end

	def create
		@question = Question.new(params.require(:question).permit(:name, :reason))
		if @question.save
			redirect_to questions_url
		else
			render action: "new"
		end
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		if @question.update_attributes(params.require(:question).permit(:name, :reason))
			redirect_to questions_path
		else
			render action: 'edit'
		end
	end

	def show
		@question = Question.find(params[:id])
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy
		redirect_to questions_url
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RgAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/questions/edit.html.erb
<h2>Edit <%= @question.name %></h2>
 
<%= form_for @question do |form| %>
  <div>
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </div>
 
  <div>
    <%= form.label :reason %><br />
    <%= form.text_field :reason %>
  </div>
 
  <p><%= form.submit %></p>
<% end %>

app/views/questions/index.html.erb
<div class="hero-unit">
  <h1>RG! Answers</h1>
  <p>Got a question?  Get the best answers!</p>
  <p><%= link_to "Ask a Question", new_question_url, :class => "brn btn-primary btn-large" %></p>
</div>
 
<table class="table table-striped">
  <thead>
    <th>Question</th>
    <th>Actions</td>
  </thead>
  <tbody>
    <% @questions.each do |single_question| %>
      <tr>
        <td>
          <strong><%= link_to single_question.name, question_path(single_question) %></strong><br />
          <%= single_question.reason %><br />
          <strong>Top Answer:</strong> <%= single_question.top_answer %>
        </td>
        <td>
          <%= link_to "Edit", edit_question_path(single_question) %>
          <%= link_to 'Destroy', single_question, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/new.html.erb
<h2>Ask a Question</h2>
<%= form_for @question do |form| %>
  <div>
    <%= form.label :name, "What is your question?" %><br />
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :reason, "Explain to users why you're asking this." %><br />
    <%= form.text_field :reason %>
  </div>
  <p><%= form.submit %></p>
<% end %>

app/views/questions/show.html.erb
<h2><%= @question.name %></h2>
<p><%= @question.reason %></p>
 
<% @question.answers.by_votes.each do |single_answer| %>
  <strong>This answer has <%= single_answer.votes %> votes.</strong><br />
  Like this answer?  <%= button_to "Vote +1", vote_question_answer_path(@question.id, single_answer.id) %>
  <p><%= single_answer.description %></p>
  <hr>
<% end %>
 
<h2>Add Answer</h2>
 
<%= form_for [@question, @question.answers.new]  do |form| %>
  <%= form.text_field :description %>
  <%= form.submit %>
<% end %>